# Generated by Django 6.0.1 on 2026-04-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=20),
            preserve_default=False,
        ),
    ]
