# Generated by Django 6.0.1 on 2026-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
