# Generated by Django 6.0.1 on 2026-04-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub_content',
            field=models.TextField(default=''),
        ),
    ]
