# Generated by Django 6.0.1 on 2026-04-15 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_sub_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
