# Generated by Django 6.0.1 on 2026-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blog_author_remove_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('program_interest', models.CharField(choices=[('youth_empowerment', 'Youth Empowerment & Skills Development'), ('digital_creative', 'Digital & Creative Skills'), ('media_broadcasting', 'Media & Broadcasting Basics'), ('talent_incubation', 'Talent Incubation')], max_length=50)),
                ('why_join', models.TextField(help_text='Tell us why you want to join this program')),
                ('experience', models.TextField(blank=True, default='', help_text='Any relevant experience or skills?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
