# Generated by Django 6.0.1 on 2026-04-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_programapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
