# Generated by Django 6.0.1 on 2026-04-28 10:42

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Gallery = apps.get_model('core', 'Gallery')
    for gallery in Gallery.objects.all():
        if not gallery.slug:
            gallery.slug = slugify(gallery.title)
            gallery.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gallery_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
