# Generated by Django 6.0.1 on 2026-04-28 10:59

from django.db import migrations
from django.utils.text import slugify


def auto_generate_slugs(apps, schema_editor):
    Gallery = apps.get_model('core', 'Gallery')
    
    # Get all items without slugs or with None/empty slugs
    items_without_slug = Gallery.objects.filter(slug__isnull=True) | Gallery.objects.filter(slug='')
    
    for item in items_without_slug:
        base_slug = slugify(item.title)
        slug = base_slug
        counter = 1
        
        # Ensure unique slug
        while Gallery.objects.filter(slug=slug).exclude(id=item.id).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        item.slug = slug
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_gallery_slugs'),
    ]

    operations = [
        migrations.RunPython(auto_generate_slugs),
    ]
