# Generated by Django 6.0.1 on 2026-05-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('sound-system', 'Sound System'), ('lighting', 'Lighting Rig'), ('stage', 'Stage Setup'), ('projection', 'Projection & AV'), ('furniture', 'Furniture & Decor'), ('catering', 'Catering Setup'), ('photography', 'Photography & Video'), ('streaming', 'Live Streaming')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('expected_guests', models.IntegerField()),
                ('space_type', models.CharField(choices=[('indoor', 'Indoor Rooms & Halls'), ('outdoor', 'Outdoor Garden Space'), ('both', 'Both (Combined)')], max_length=50)),
                ('special_requirements', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equipment', models.ManyToManyField(to='core.equipment')),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
    ]
