# Generated by Django 6.0.1 on 2026-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_equipment_equipmentorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.AlterField(
            model_name='equipmentorder',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='core.equipment'),
        ),
        migrations.AlterField(
            model_name='equipmentorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
