# Generated by Django 6.0.1 on 2026-05-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_host_alter_equipmentorder_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentorder',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
