# Generated by Django 6.0.1 on 2026-05-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_equipmentorder_equipment_delete_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentorder',
            name='selected_services',
            field=models.TextField(blank=True, help_text='Services requested by the client', null=True),
        ),
    ]
