# Generated by Django 6.0.1 on 2026-05-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contactmessage_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
