# Generated by Django 6.0.5 on 2026-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_contactmessage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=20),
        ),
    ]
